# SPDX-FileCopyrightText: 2026 NXLX.Systems and contributors
# SPDX-License-Identifier: Apache-2.0
# Keep the system log across restarts, so the cause of an unexpected restart (power, heat, a crash) can be read
# afterwards with `journalctl -b -1`. Raspberry Pi OS keeps it in memory only (40-rpi-volatile-storage.conf);
# this file sorts after it and wins. Capped so it cannot fill or wear the card noticeably. With the read-only
# root (pvj-rootfs) /var is in memory, so the log is again lost at a restart.
[Journal]
Storage=persistent
SystemMaxUse=64M
SystemKeepFree=500M
