# SPDX-FileCopyrightText: 2026 NXLX.Systems and contributors
# SPDX-License-Identifier: Apache-2.0
name: Security tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  endpoints:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.2']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - run: tests/security_test.sh
